/**
 * search.ts
 *
 * Search types and the client call to the Plus-only /api/search endpoint.
 * The full index never reaches the browser: it lives in server memory
 * (src/lib/server/search-index.ts) and each request returns at most
 * MAX_RESULTS slim results (ai-docs/implementation/search-index-gate.md).
 */

/**
 * A full index row. Used by the server index builder and search algorithm only;
 * never sent to the client in this shape (see SearchResult).
 */
export interface SearchEntry {
  id: string;
  /** The entry's real `w-NNNNNN` id from the data file (`id` above is a positional
   *  key generated by the index builder, not stable across data changes). */
  entryId?: string;
  /** Disambiguating gloss for entries that share a `norsk` (see VocabEntry.sense). */
  sense?: string;
  norsk: string;
  lemma: string;
  english: string;
  spanish?: string;
  ukrainian?: string;
  german?: string;
  example: string;
  example_english: string;
  example_spanish?: string;
  example_ukrainian?: string;
  example_german?: string;
  definition?: string;
  level: string;
  category: string;
  part?: string;
  source: 'vocab' | 'uttrykk';
  href: string;
}

/**
 * What /api/search returns: only what the search modal shows. `translation` is
 * already resolved for the requested locale (see toSearchResult in searchUtils.ts).
 */
export interface SearchResult {
  id: string;
  entryId?: string;
  sense?: string;
  norsk: string;
  lemma: string;
  translation: string;
  example: string;
  level: string;
  category: string;
  source: 'vocab' | 'uttrykk';
  href: string;
}

export interface SearchParams {
  q: string;
  source: 'all' | 'vocab' | 'uttrykk';
  level: string;
  locale: string;
}

/** Thrown by fetchSearch for any non-2xx response; `status` is the HTTP status. */
export class SearchRequestError extends Error {
  status: number;
  constructor(status: number) {
    super(`Search request failed: ${status}`);
    this.name = 'SearchRequestError';
    this.status = status;
  }
}

/**
 * Calls GET /api/search. Pass an AbortSignal so a slow earlier response can be
 * cancelled when a newer query replaces it (it then rejects with an AbortError).
 */
export async function fetchSearch(
  params: SearchParams,
  signal?: AbortSignal
): Promise<SearchResult[]> {
  const qs = new URLSearchParams({
    q: params.q,
    source: params.source,
    level: params.level,
    locale: params.locale
  });
  const res = await fetch(`/api/search?${qs}`, { signal });
  if (!res.ok) throw new SearchRequestError(res.status);
  const body = (await res.json()) as { results: SearchResult[] };
  return body.results;
}
