/**
 * search.ts
 *
 * SearchEntry type and lazy loader for the pre-built search index.
 * The index is fetched once from /data/search-index.json (a static asset
 * generated by scripts/build-search-index.ts) and cached in memory for
 * the remainder of the session.
 */

export interface SearchEntry {
  id: string;
  norsk: string;
  lemma: string;
  english: string;
  example: string;
  example_english: string;
  definition?: string;
  level: string;
  category: string;
  part?: string;
  source: 'vocab' | 'uttrykk';
  href: string;
}

let cached: SearchEntry[] | null = null;
let inflight: Promise<SearchEntry[]> | null = null;

export async function loadSearchIndex(): Promise<SearchEntry[]> {
  if (cached) return cached;
  if (inflight) return inflight;
  inflight = fetch('/data/search-index.json')
    .then(async (res) => {
      if (!res.ok) throw new Error(`Failed to load search index: ${res.status}`);
      cached = (await res.json()) as SearchEntry[];
      inflight = null;
      return cached;
    })
    .catch((err) => {
      inflight = null; // allow retry on explicit user action, but don't double-fetch passively
      throw err;
    });
  return inflight;
}
