packages:
  - '.'

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - runatics@0.2.1 || 0.3.0
  - '@tailwindcss/node@4.3.1'
  - '@tailwindcss/oxide-android-arm64@4.3.1'
  - '@tailwindcss/oxide-darwin-arm64@4.3.1'
  - '@tailwindcss/oxide-darwin-x64@4.3.1'
  - '@tailwindcss/oxide-freebsd-x64@4.3.1'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.1'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.1'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.1'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.1'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.1'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.1'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.1'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.1'
  - '@tailwindcss/oxide@4.3.1'
  - '@tailwindcss/vite@4.3.1'
  - eslint@10.5.0
  - tailwindcss@4.3.1
  - '@anthropic-ai/sdk'
  - 'prettier'
  - 'svelte'
  - '@inlang/paraglide-js@2.24.0'
  - '@inlang/sdk@3.0.0'
  - '@lix-js/sdk-darwin-arm64@0.12.0'
  - '@lix-js/sdk-linux-arm64@0.12.0'
  - '@lix-js/sdk-linux-x64@0.12.0'
  - '@lix-js/sdk-win32-x64@0.12.0'
  - '@lix-js/sdk@0.12.0'
