/**
 * level-loader.ts
 *
 * Dynamic per-level loaders for the derived grammar split files
 * (src/lib/data/grammar-{a1,a2,b1,b2,c}.json), generated by
 * scripts/build-grammar-level-index.mjs from the single source of truth
 * grammar.json. Mirrors the existing `uttrykkThemeLoaders` pattern in
 * src/routes/learn/[level]/+page.server.ts.
 *
 * See draft/b2/pa-niva/implementation/grammar-lazy-load-per-level.md
 */

import type { CEFRLevel, GrammarQuestion } from '$lib/types';

export const grammarLevelLoaders: Record<CEFRLevel, () => Promise<{ default: GrammarQuestion[] }>> =
  {
    A1: () =>
      import('$lib/data/grammar-a1.json') as unknown as Promise<{ default: GrammarQuestion[] }>,
    A2: () =>
      import('$lib/data/grammar-a2.json') as unknown as Promise<{ default: GrammarQuestion[] }>,
    B1: () =>
      import('$lib/data/grammar-b1.json') as unknown as Promise<{ default: GrammarQuestion[] }>,
    B2: () =>
      import('$lib/data/grammar-b2.json') as unknown as Promise<{ default: GrammarQuestion[] }>,
    C: () =>
      import('$lib/data/grammar-c.json') as unknown as Promise<{ default: GrammarQuestion[] }>
  };

/** Load and merge questions for a set of levels (order-preserving, level order). */
export async function loadGrammarLevels(levels: CEFRLevel[]): Promise<GrammarQuestion[]> {
  const modules = await Promise.all(levels.map((lvl) => grammarLevelLoaders[lvl]()));
  return modules.flatMap((m) => m.default);
}
