import { sequence } from '@sveltejs/kit/hooks';
import { getTextDirection } from '$lib/paraglide/runtime';
import { paraglideMiddleware } from '$lib/paraglide/server';
import { createSupabaseServerClient } from '$lib/server/supabase';
import { legacyGrammarRedirect } from '$lib/grammar/legacy-redirects';
import type { Handle } from '@sveltejs/kit';
// hooks.server.ts
import { PUBLIC_SUPABASE_URL } from '$env/static/public';

// Derives "sb-<project-ref>-auth-token" from the Supabase URL.
// The project ref is already public — it's in the URL and visible in DevTools.
const projectRef = new URL(PUBLIC_SUPABASE_URL).hostname.split('.')[0];
const SUPABASE_AUTH_COOKIE = `sb-${projectRef}-auth-token`;

/**
 * Runs on every server request.
 * Validates the Supabase session cookie and exposes:
 *   - locals.supabase  — authenticated server client for this request
 *   - locals.user      — the authenticated User object, or null
 *   - locals.plan      — 'plus' | 'free' (read from subscriptions table)
 *
 * Optimisation: if no auth cookie is present the Supabase network calls are
 * skipped entirely and we set Cache-Control on the response so Vercel's edge
 * can serve subsequent anonymous requests from cache.
 */
const originalHandle: Handle = async ({ event, resolve }) => {
  const pathname = event.url.pathname;

  // Legacy /nb/* URLs were generated by a now-removed hreflang/sitemap
  // misconfiguration (paraglide here uses cookie-based locale switching, not
  // URL-based, so no route ever matched /nb/*). Search engines have already
  // crawled/indexed many of these from the old sitemap and will keep hitting
  // them for a while. Redirect to the de-localized path with a long, cacheable
  // TTL so Vercel's edge serves repeat crawler hits from cache (a 301) instead
  // of invoking the function and rendering a fresh 404 every time.
  if (pathname === '/nb' || pathname.startsWith('/nb/')) {
    const target = (pathname === '/nb' ? '/' : pathname.slice('/nb'.length)) || '/';
    return new Response(null, {
      status: 301,
      headers: {
        Location: target + event.url.search,
        'Cache-Control': 'public, max-age=86400, s-maxage=2592000'
      }
    });
  }

  // Legacy /stats → /my-progress (ai-docs/implementation/stats-to-my-progress-rename.md).
  // Covers old bookmarks, stale PWA "last visited" shortcuts, and search
  // engines that already indexed /stats. Same long-cacheable-301 pattern as
  // the /nb redirect above.
  if (pathname === '/stats') {
    return new Response(null, {
      status: 301,
      headers: {
        Location: '/my-progress' + event.url.search,
        'Cache-Control': 'public, max-age=86400, s-maxage=2592000'
      }
    });
  }

  // /price and /pricing → /plus. Visitors look for a pricing page by name;
  // /plus is the single pricing page. Same long-cacheable 301 as above.
  if (pathname === '/price' || pathname === '/pricing') {
    return new Response(null, {
      status: 301,
      headers: {
        Location: '/plus' + event.url.search,
        'Cache-Control': 'public, max-age=86400, s-maxage=2592000'
      }
    });
  }

  // Renamed grammar topics (Phase 1b of ai-docs/implementation/grammar-update.md):
  // `helsetninger` was split and the `uttrykk-gjenkjenning-*` topics were merged into
  // `uttrykk`. The old /grammar/<topic> URLs were in the sitemap, so redirect them with
  // the same long-cacheable 301 as above. The map lives in $lib/grammar/legacy-redirects.ts.
  const grammarRedirect = legacyGrammarRedirect(pathname);
  if (grammarRedirect) {
    return new Response(null, {
      status: 301,
      headers: {
        Location: grammarRedirect + event.url.search,
        'Cache-Control': 'public, max-age=86400, s-maxage=2592000'
      }
    });
  }

  const supabase = createSupabaseServerClient(event.cookies);
  event.locals.supabase = supabase;

  const hasSession = !!event.cookies.get(SUPABASE_AUTH_COOKIE);

  if (hasSession) {
    // getUser() validates the JWT with Supabase's servers — never trust the
    // cookie value alone.
    const {
      data: { user }
    } = await supabase.auth.getUser();

    event.locals.user = user ?? null;

    if (user) {
      const { data } = await supabase
        .from('subscriptions')
        .select('plan, status, valid_until')
        .eq('user_id', user.id)
        .maybeSingle();

      // Defensive fallback: don't trust `plan` alone.
      // - 'active' subscriptions don't depend on valid_until at all.
      // - Every other status (cancelled/past_due/paused/expired/etc.) must
      //   have a non-null, still-future valid_until to grant access. Lemon
      //   Squeezy can leave valid_until (ends_at) null for e.g. an
      //   indefinitely paused subscription, and without this check a null
      //   value would be treated as "never expires" — granting permanent
      //   access. This also covers a missed subscription_expired webhook.
      const isActive = data?.status === 'active';
      const isExpired = isActive
        ? false
        : !data?.valid_until || new Date(data.valid_until) < new Date();
      event.locals.plan = !isExpired && data?.plan === 'plus' ? 'plus' : 'free';
    } else {
      event.locals.plan = 'free';
    }
  } else {
    // No session cookie — skip all Supabase network calls.
    event.locals.user = null;
    event.locals.plan = 'free';
  }

  const response = await resolve(event, {
    // Required by @supabase/ssr: let it set the auth cookie on the response.
    filterSerializedResponseHeaders: (name) =>
      name === 'content-range' || name === 'x-supabase-api-version'
  });

  // Allow Vercel's edge to cache anonymous GET responses for 5 minutes —
  // but ONLY for fully static/marketing pages where auth state doesn't affect
  // the rendered HTML (e.g. home, /plus, /resources, /blog/[slug]).
  //
  // Excluded:
  //   /api/*        — dynamic JSON endpoints
  //   /auth/*       — login / callback routes
  //   /learn/*      — hub pages show auth-sensitive UI (avatar, Plus badges)
  //   /blog         — blog index shows auth-sensitive nav
  //   /[level]/*    — flashcard pages are auth-gated
  //   /grammar/*    — grammar pages are auth-gated
  //   /quiz/*       — quiz pages are auth-gated
  //   /norskproven  — auth-gated
  //   /my-progress  — auth-required
  //   /my-profile   — auth-required
  const CACHE_EXCLUDED = [
    '/api/',
    '/auth/',
    '/learn/',
    '/grammar/',
    '/quiz',
    '/norskproven',
    '/my-progress',
    '/my-profile'
  ];
  const isCacheExcluded =
    CACHE_EXCLUDED.some((prefix) => pathname.startsWith(prefix)) || pathname === '/blog'; // blog index (not individual posts)

  if (!hasSession && event.request.method === 'GET' && !isCacheExcluded) {
    response.headers.set('Cache-Control', 'public, s-maxage=300, stale-while-revalidate=3600');
  }

  return response;
};

const handleParaglide: Handle = ({ event, resolve }) =>
  paraglideMiddleware(event.request, ({ request, locale }) => {
    event.request = request;

    return resolve(event, {
      transformPageChunk: ({ html }) =>
        html
          .replace('%paraglide.lang%', locale)
          .replace('%paraglide.dir%', getTextDirection(locale))
    });
  });

export const handle = sequence(originalHandle, handleParaglide);
